//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRNotificationEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationRecipient
    {
        public Nullable<System.Guid> NotificationId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> NotificationExpiry { get; set; }
        public int Id { get; set; }
    }
}
