//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRNotificationEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationDetail
    {
        public System.Guid NotificationId { get; set; }
        public int NotificationTypeId { get; set; }
        public string NotificationNumber { get; set; }
        public int CompanyId { get; set; }
        public string NotificationStatus { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public System.Guid CreatedUpdatedBy { get; set; }
        public string CreatedUpdatedByName { get; set; }
    }
}
